version: 3
vars:
  VENV_DIR: '.venv'
  ACTIVATE: 'source {{ .VENV_DIR }}/bin/activate'
  SKIP_INSTALL: '{{ .SKIP_INSTALL }}'

tasks:

  setup_venv:
    run: once
    cmds: ['python3 -m venv {{ .VENV_DIR }}']
    status:
      - 'test -n "{{ .SKIP_INSTALL }}"'

  install:
    deps: [setup_venv]
    run: when_changed
    vars:
      EXTRAS: ""
      EXTRAS_REQ:
        sh: 'test -n "{{ .EXTRAS }}" && echo "\[ {{.EXTRAS }}\]" || echo ""'
    status:
      - 'bash -c "test -n \"{{ .SKIP_INSTALL }}\""'
    cmds:
      - 'bash -c "{{.ACTIVATE}} && pip install .{{ .EXTRAS_REQ }}"'

  clean:
    run: once
    cmds:
      - 'rm -rf "{{.VENV_DIR}}" .tox'

  build:
    deps:
      - setup_venv
      - task: install
        vars:
          EXTRAS: build
    cmds:
      - bash -c '{{.ACTIVATE}} && pip wheel .'

  maybe_bump:
    deps:
      - setup_venv
      - task: install
        vars:
          EXTRAS: release
    cmds:
      - bash -c '{{.ACTIVATE}} &&  avakas bump . auto --flavor git-native --branch main

  test:
    deps:
      - setup_venv
      - task: install
        vars:
          EXTRAS: test
    cmds:
      - bash -c '{{ .ACTIVATE }} && tox . {{.CLI_ARGS}}'
